version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/web
    depends_on:
     - php

  php:
    image: docker.io/php:7.2.34-fpm
    volumes:
      - ./:/web
    working_dir: /web
